defaults: &DEFAULTS
  metadata_engines: [ "DataciteEngine"]
  shared_resource_model: StashEngine::Resource

development: &DEVELOPMENT
  <<: *DEFAULTS

local_engines:
  <<: *DEVELOPMENT

test:
  <<: *DEFAULTS

stage:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS