development: &DEVELOPMENT
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development_local_engines:
  <<: *DEVELOPMENT

test:
  adapter: mysql2
  database: stash_prototype_test
  username:
  password:
  host: localhost
  port: 3000

production:
  adapter: mysql2
  database: stash_prototype_dev
  username:
  password:
  host: localhost
  port: 3000
