development:
  adapter: mysql2
  database: stash_prototype_development
  username:
  password:
  host: localhost
  port: 3000

test:
  adapter: mysql2
  database: stash_prototype_test
  username:
  password:
  host: localhost
  port: 3000

production:
  adapter: mysql2
  database: stash_prototype_dev
  username:
  password:
  host: localhost
  port: 3000
